model:
  height: 8
  width: 8
  class: "BasicModel"
view:
  height: 500
  width: 500
  classes:
  - "SquarePixelsWithBorder"
controller:
  classes:
  - "MulticolouredController"
  - "MakeMeGrey"
  - "BasicController"
